apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
stringData: # entries will be base64 encoded by kubernetes 
  apikey: my_api_key
  apisecret: my_api_secret
---
apiVersion: v1
kind: Pod
metadata:
  name: mounting-secrets-as-volumes-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: api-config-volume
      mountPath: /api-secrets
      readOnly: true
  volumes:
  - name: api-config-volume
    secret:
      secretName: api-secrets