apiVersion: v1
kind: Secret
metadata:
  name: using-string-data-section
stringData: # entries will be base64 encoded by kubernetes 
  foo: bar
  mac: cheese
---
apiVersion: v1
kind: Pod
metadata:
  name: using-string-data-section-pod
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: using-string-data-section