apiVersion: v1
kind: Secret
metadata:
  name: using-data-section
data:
  apikey: Zm9vYmFy # must be base 64 encoded
---
apiVersion: v1
kind: Pod
metadata:
  name: using-data-section-pod
spec:
  containers:
  - name: nginx
    image: nginx
    env: # expose secret api key as an env var
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: using-data-section
          key: apikey